export const ROUTES = {
  HOME: '/',
  FEED: '/feed',
  EXPLORE: '/explore',
  MESSAGES: '/messages',
  MESSAGE_DETAIL: (conversationId) => `/messages/${conversationId}`,
  PROFILE: (id) => id ? `/profile/${id}` : '/profile',
  PROFILE_BASE: '/profile',
  SETTINGS: '/settings',
  NOTIFICATIONS: '/notifications',
  GROUPS: '/groups',
  NEWS: '/news',
  FAQ: '/faq',
  HELP: '/help',
  AI_CHAT: '/ai-chat',
  CLIPS: '/clips',
  VIBE: '/vibe',
  VIBE_PROJECTS: '/vibe/projects',
  VIBE_PROJECTS_CREATE: '/vibe/projects/create',
  VIBE_PROJECT_DETAIL: (id) => `/vibe/projects/${id}`,
  VIBE_TEMPLATES: '/vibe/templates',
  AUTH: '/auth',
  LOGIN: '/auth',
  REGISTER: '/auth/register',
  DEVELOPER_PROFILE: (id) => id ? `/dev/${id}` : '/dev',
};
